from __future__ import annotations

from .established_year_parser import parse_established_year
from .fee_parser import (
    extract_fees,
    extract_total_fees,
    extract_registration_fees,
    extract_tuition_fees,
    extract_admission_fees,
    extract_all_fee_types,
)
from .placement_parser import (
    extract_placements_info,
    extract_recruiters_list,
    extract_alumni_list,
)
from .course_parser import (
    extract_courses,
    extract_course_details,
    extract_course_detail_rows,
    extract_course_details_by_context,
    parse_course_detail_text,
    extract_specializations,
    extract_cutoffs,
    extract_rankings,
)
from .misc_parser import (
    extract_location_details,
    extract_contact_info,
    extract_admission_details,
    extract_infrastructure_booleans,
    extract_hostels_list,
    extract_scholarships_list,
    extract_rankings_list,
    extract_reviews_list,
    extract_gallery_media,
    extract_downloads_list,
    extract_news_list,
    extract_events_list,
    extract_faqs_list,
    extract_documents_required,
    extract_faculty_list,
    extract_emails,
    extract_phones,
)
from .regex_patterns import URL_PATTERN

__all__ = [
    "parse_established_year",
    "extract_fees",
    "extract_total_fees",
    "extract_registration_fees",
    "extract_tuition_fees",
    "extract_admission_fees",
    "extract_all_fee_types",
    "extract_placements_info",
    "extract_recruiters_list",
    "extract_alumni_list",
    "extract_courses",
    "extract_course_details",
    "extract_course_detail_rows",
    "extract_course_details_by_context",
    "parse_course_detail_text",
    "extract_specializations",
    "extract_cutoffs",
    "extract_rankings",
    "extract_location_details",
    "extract_contact_info",
    "extract_admission_details",
    "extract_infrastructure_booleans",
    "extract_hostels_list",
    "extract_scholarships_list",
    "extract_rankings_list",
    "extract_reviews_list",
    "extract_gallery_media",
    "extract_downloads_list",
    "extract_news_list",
    "extract_events_list",
    "extract_faqs_list",
    "extract_documents_required",
    "extract_faculty_list",
    "extract_emails",
    "extract_phones",
    "URL_PATTERN",
]
